### ISSUE TITLE
Inspecting custom messages using 'ign topic --echo --topic /some_topic'

### ISSUE THREAD

**Issue by lnotspotl** [gazebosim/gz-transport#346] opened 2022-08-09 13:05 UTC
Hi,

is it possible to use the ```ign topic --echo --topic /some_topic``` command to inspect user defined messages published on some topic?

In one of my projects, I have a ```spot_msgs/RobotState``` message defined, I use this message in a custom Ignition plugin that publishes data on topic ```/robot_state```. I know that the messages do get published, since I use some other node that processes them.

Are there some environment variables that need to be set in order for the aforementioned command to work or is it the case that message inspection via the ```ign topic --echo --topic /my_topic``` command only works when the published messages are part of the **gz-msgs** package?

Thanks
lnotspotl

![image](https://user-images.githubusercontent.com/82883398/183653453-c7491448-b077-4878-8bcf-5b65a074743d.png)

### edit:
I have tried the following **ign topic**  versions and none of them work.
![image](https://user-images.githubusercontent.com/82883398/183655897-f82cdd84-aac1-43d2-9c85-b5615c657142.png)

**Comment by chapulina** [comment] 2022-08-10 02:47
That's a known limitation of custom messages. This issue is a duplicate of 

* https://github.com/gazebosim/gz-tools/issues/5

**Closed** 2022-08-17 21:26 UTC
